"""提示词统一入口（LangChain 模板管理，风格同 pyannote_diarization/prompts）。"""
from prompts.assistant import (
    ASSISTANT_SYSTEM_TEMPLATE,
    ASSISTANT_SYSTEM_WITH_TOOLS_TEMPLATE,
    ASSISTANT_CHAT_PROMPT,
    ASSISTANT_CHAT_PROMPT_WITH_TOOLS,
)

__all__ = [
    "ASSISTANT_SYSTEM_TEMPLATE",
    "ASSISTANT_SYSTEM_WITH_TOOLS_TEMPLATE",
    "ASSISTANT_CHAT_PROMPT",
    "ASSISTANT_CHAT_PROMPT_WITH_TOOLS",
]
